services:
  go-app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: go-app
    depends_on:
      - mysql
    env_file:
      - .env
    ports:
      - '8080:8080'

  mysql:
    image: mysql:8.0
    container_name: mysql-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  mysql_data:
